# -*- coding: utf-8 -*-
"""Try-nlp

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1vVh65Xa-bpwl_g5AM24huN6mabGOy4_l
"""

pip install git+https://github.com/haven-jeon/PyKoSpacing.git

pip install git+https://github.com/ssut/py-hanspell.git

sent = '김철수는 극중 두 인격의 사나이 이광수 역을 맡았다. 철수는 한국 유일의 태권도 전승자를 가리는 결전의 날을 앞두고 10년간 함께 훈련한 사형인 유연재(김광수 분)를 찾으러 속세로 내려온 인물이다. 어쩔티비 알잘딱깔센 가즈아.'

new_sent = sent.replace(" ", '') # 띄어쓰기가 없는 문장 임의로 만들기
print(new_sent)

from pykospacing import Spacing
spacing = Spacing()
kospacing_sent = spacing(new_sent) 

print(sent)
print(kospacing_sent)

from hanspell import spell_checker

sent = "으쩌라고 어쩔티비 알잘딱깔센 으쩔티비" #반려
spelled_sent = spell_checker.check(sent)

hanspell_sent = spelled_sent.checked
print(hanspell_sent)

pip install customized_konlpy

pip install soynlp

from soynlp.normalizer import *


from ckonlpy.tag import Twitter
twitter = Twitter()
words=twitter.morphs(repeat_normalize(emoticon_normalize('ㅋㅋㅋㅋㅋㅋㅋㅋ어쩔티비 그냥 밥이나 먹어 하하하하')))
print(words)
twitter.add_dictionary('어쩔티비','Noun')
print(repeat_normalize('ㅋㅋㅋㅋㅋㅋㅋㅋ어쩔티비 그냥 밥이나 먹어 하하하하'))
words=twitter.morphs(repeat_normalize('ㅋㅋㅋㅋㅋㅋㅋㅋ어쩔티비 그냥 밥이나 먹어 하하하하')) # 의성어와 신조어가 붙어있는 경우
print(words)
words=twitter.morphs(repeat_normalize('ㅋㅋㅋㅋㅋㅋㅋㅋ어쩔티비그냥 밥이나 먹어 하하하하')) # 신조어와 단어가 붙어있는 경우
print(words)
words=twitter.morphs(repeat_normalize('ㅋㅋㅋㅋㅋㅋㅋㅋ어쩔티비그냥밥이나먹어하하하하')) # 신조어와 단어가 붙어있는 경우
print(words)